### ISSUE TITLE
query addresses/buildings into separate by census tract

### ISSUE THREAD

**Issue by ian29** [osmlab/dcbuildings#1]
@lxbarth had a poorly fleshed-out thought on the way to work this morning. 

The address data contains a field for the census tract that each address lies inside of. Using [psycopg](http://initd.org/psycopg/), we could potentially
1. write a query that returned all the addresses in one census tract
2. read the resultant table into memory and join against buildings (also in memory)
3. repeat steps 1 and 2 for each census tract

This way we only have to read 1 census tract's worth of address into memory to perform the spatial join against the building data set. 

Thoughts?

**Comment by iandees** [comment]
Helping the spatial join by making the work area smaller would speed things up, but you shouldn't be running into memory issues on 60MB shapefiles. That sounds like a fiona bug to me. Try using shapely and see if you run into issues there, too?

**Comment by ian29** [comment]
hrm, @lxbarth you were seeing ~1GB in memory usage right?

**Comment by lxbarth** [comment]
@ian29 - yeah, I've been thinking about this along the same lines.

I've done some more experimenting this weekend and while I didn't get the memory usage under control (still clocking in at 2.2G), I sped up the building+address joining considerably using RTree. The script is now finishing in about 2 minutes, that includes reading and indexing shapefiles and a full building + address join.

I've further narrowed down the memory consumption problem not to fiona, but to shapely.Converting all features (each building and each address) into Shapely objects is just very expensive.

The memory issue will absolutely be exacerbated by starting to generate OSM files. It could be improved by only reading and indexing _buildings_ tract by tract similar to what you suggest, but I suspect this will make the process very slow.

I'd like to pick @tmcw's brain on this, but I'm starting to think this type of task is what PostGIS is for and we should just use it. Specifically instead of reading directly from shape files we should import them first into PostGIS, then do all join operations as PostGIS queries. We can use Python to solve the more intricate problems like 2 or more addresses per buildings and formatting.

@pnorman also pointed me to his [addressmerge](https://github.com/pnorman/addressmerge) project. He's got some plans for it that could be helpful for the DC buildings import.

**Comment by lxbarth** [comment]
@tmcw says try [prepared geometries](http://toblerity.github.io/shapely/manual.html#prepared-geometry-operations)

**Comment by lxbarth** [comment]
This is done now. Script generates separate OSM files, one per census tract. Todo: add addresses.
