### ISSUE TITLE
Discount existing buildings

### ISSUE THREAD

**Issue by lxbarth** [osmlab/dcbuildings#2]
- Remove buildings that already exist in OSM from importable .osm files

**Comment by andinocl** [comment]
I think this should be conditional. We should discount existing buildings, but specifically include buildings in which the rooftop poly has changed.  This will be made more complicated by the fact that the simplify operation (and/or the manual tracing done by an OSMer) will introduce a margin of error.

**Comment by lxbarth** [comment]
@andinocl - I don't think we should discount buildings at first at all, but just periodically generate a map [like so](http://www.sixpica.com/osm/2013/05/19/scope-of-work-cool-new-tools/) showing where we're still missing buildings. Much easier, no?

**Comment by andinocl** [comment]
@lxbarth it's not so much about the missing buildings that I'm preoccupied about, it's more footprint changes between imports so you have a big red flag where human intervention is required. It's a relatively small problem set, and I agree it's outside of the scope for finishing the building import. It's potentially a tool to think about if the scripts can be at all universalized to other similar import sets, but probably one that should be packaged separately in order to not commit too many cycles for a niche output.

**Comment by lxbarth** [comment]
>  it's more footprint changes between imports so you have a big red flag where human intervention is required.

O, so you mean identifying buildings that have been substantially updated in the latest DC GIS dataset?

**Comment by andinocl** [comment]
Exactly.  The way I was doing the (admittedly manual) compare between GIS sets was to use QGIS to polygonize the lines that were generated by the postGIS linestring query and then view the osm layer over the dcgis layer.  That was good for showing me where 1.) buildings hadn't yet been imported, 2.) where new buildings had been added where previous was blank land and 3.) footprint changes where the new building had nodes that fell outside the bounds of the old building (or, more likely, the osm version had been added with lack of accuracy/precision).  Basically, there were color cues of the buildings "shining through" the osm layer.

That method was bad at #3 and worse at the case where the new building had footprint changes but had no nodes outside of the osm building.  I played around with differences and symdifferences, but could never quite get it to work because GIS isn't the right way to do that calculation.  Where it'd be useful is looking at a big area where there are few changes expected (e.g. a nearly complete DC import, updates to existing imports).  I think I have a basic framework for how to tackle the problem but it's 1.) a problem for another day and 2.) beyond my ability to code. Either way, outside the scope of this proposal, I'd say.

**Comment by jremillard** [comment]
This is outside the scope of the import. But for #3, you can probably wrangle QGIS to filter on buildings that overlap, but have a certain percentage different in area, perimeter, center of mass, number of points, etc to find the buildings that are in OSM but have very different footprints in the DC data.

**Comment by lxbarth** [comment]
Let's hold on this for now.
